version: "3.7"

services:
  express-mysql:
    image: mysql:5.7
    container_name: express-mysql #always
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express-db
      MYSQL_USER: express
      MYSQL_PASSWORD: 123456
    ports:
      - "3301:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - common

  express-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    restart: unless-stopped #always
    container_name: express-api
    command: "npm run dev"
    depends_on:
      - express-mysql
    networks:
      - common

  express-adminer:
    image: adminer
    restart: always
    container_name: express-adminer
    ports:
      - 8081:8080
    depends_on:
      - express-mysql
    networks:
      - common
#http://localhost:8081/?server=express-mysql&username=express

volumes:
  db:

networks:
  common:
